spring.application.name=securitydemo
spring.security.user.password=demo@123
spring.security.user.name=admin

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

spring.app.jwtSecret=MySecretKeyForJwtAuthentication123456789dfbdfgsdfsdfhg
spring.app.jwtExpirationMs=3600000


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.example.securitydemo=DEBUG